import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Experiance from "./Experiance/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "First NextApp",
  description: "Generated by First NextApp",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Experiance/>
        {children}
      </body>
    </html>
  );
}
