import React from 'react'
import Script from 'next/script'

const contact = () => {
  return (
    <div>
      <Script>
        {
          `alert("Welcome To Contact Page !");`
        }
      </Script>
      

      This Is a contact Page 2
    </div>
  )
}

export default contact

export const metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
};
