import React from 'react';
import Image from 'next/image';

const about = () => {
  return (
    <div className='container'>
      <Image
        className='mx-auto py-10'
        width={100}
        height={100}
        src="https://th.bing.com/th/id/OIP.sfhCq8XCnmtjiYWp8pa5JAHaDt?rs=1&pid=ImgDetMain"
        alt="Description of the image"
      />
      <p>This Is an About Page</p>
    </div>
  );
};

export default about;

export const metadata = {
  title: "Description About Page",
  description: "Generated by Description About Page",
};
