import React from 'react';
import Image from 'next/image';

const about = () => {
  return (
    <div className='container size-80 bg-red-300 relative'>
      <Image
        className='mx-auto py-10 object-contain'
       
        fill={true}
        src="https://smartslider3.com/wp-content/uploads/slider132/image-slider-with-thumbnail1.jpeg"
        alt="Description of the image"
      />
      <p>This Is an About Page</p>
    </div>
  );
};

export default about;

export const metadata = {
  title: "Description About Page",
  description: "Generated by Description About Page",
};
